expname: kaggle_cars
data:
  datadir: data/kaggle_cars/train
  type: image_folder
  imsize: 64
  white_bkgd: False
  radius: 9.5,10.5
  near: 7.5
  far: 12.5
  fov: 10.
  umin: 0
  umax: 0.25
  vmin: 0.32898992833716556 # 70 deg
  vmax: 0.45642212862617093   # 85 deg
training:
  take_model_average: false # TODO: remove
  video_every: 1000
