expname: mega_cars
data:
  datadir: data/megacars/train
  type: image_folder
  imsize: 128
  white_alpha_bg: True
  radius: 9.5,10.5
  near: 7.5
  far: 12.5
  fov: 10.
  umin: 0
  umax: 1
  vmin: 0.0
  vmax: 0.0
  crop: 80
training:
  take_model_average: false # TODO: remove
  video_every: 1000
